### ISSUE TITLE
После разворачивания образа Report Portal не удается залогиниться под учеткой администратора

### ISSUE THREAD

**Issue by evgsemenov** [evgsemenov/5.2.3.1-Patterns-Card-Delivery#6]
После разворачивания образа Report Portal не удается залогиниться под учеткой администратора.  Появляются сообщения об успешном входе либо об ошибке сервера, но дальше страницы логина пройти не удается.

Шаги воспроизведения:
1. Скачать репо
2. Перейти в ветку report-portal
3. Запустить в консоли команду `docker-compose -p reportportal up -d --force-recreate`
4. После успешного разорачивания образа открыть в браузере адрес [http://localhost:8080](http://localhost:8080)
5. В поле ADMIN ввести "superadmin'
6. В поле PASSWORD ввести "erebus"
7. Нажать кнопку LOGIN 

ОР: 
Происходит авторизация и переход на новую страницу сервиса

ФР:
На странице появляются сообщения об успешной авторизации, либо об ошибке сети.  Редайректа со страницы логина не осуществляется.
![Screenshot_3](https://user-images.githubusercontent.com/39197351/128889986-3a10632b-5fc6-4255-b0f1-0d050ef7805a.png)
![Screenshot_4](https://user-images.githubusercontent.com/39197351/128890009-dfb6a1ac-9af0-4fd7-bb1f-7ab33f4057ca.png)

**Comment by andrew-pahomov** [comment]
Добрый вечер, Прошу указать окружение.

**Comment by evgsemenov** [comment]
@andrew-pahomov  Добрый вечер.
Win 10 Pro x64 (10.0.19043 Сборка 19043)
Firefox 91.0 (64-битный)

В режиме "Инкогнито" тоже самое.

**Comment by andrew-pahomov** [comment]
У Вас настройка контейнеров докера под Linux, посмотрите [этот раздел](https://reportportal.io/docs/Deploy-ReportPortal-with) документации.
